// Starter recipe library — diverse cuisines & food groups, adaptable for a 5yo and a 2yo.
// categories: produce, protein, dairy, pantry, frozen, spice
// foodGroups are loose tags used for the "variety" nudge.
const RECIPES = [
  {
    id: 'chicken-veggie-fried-rice',
    name: 'Chicken & Veggie Fried Rice',
    cuisine: 'Asian-inspired',
    mealType: 'dinner',
    prepMin: 25,
    freezerFriendly: true,
    foodGroups: ['protein-poultry', 'veg', 'grain-rice'],
    toddlerNotes: 'Chop veg very small (pea-sized) and go light on soy sauce before splitting off the toddler portion.',
    steps: [
      'Cook rice (or use day-old rice) and set aside.',
      'Scramble an egg in a hot pan, remove, set aside.',
      'Stir-fry diced chicken until cooked, add diced carrot & peas.',
      'Add rice, egg, soy sauce and garlic; toss until hot through.',
    ],
    ingredients: [
      { name: 'rice', qty: '300', unit: 'g', cat: 'pantry' },
      { name: 'chicken breast', qty: '350', unit: 'g', cat: 'protein' },
      { name: 'egg', qty: '2', unit: '', cat: 'dairy' },
      { name: 'carrot', qty: '2', unit: '', cat: 'produce' },
      { name: 'frozen peas', qty: '150', unit: 'g', cat: 'frozen' },
      { name: 'garlic', qty: '2', unit: 'cloves', cat: 'produce' },
      { name: 'soy sauce', qty: '2', unit: 'tbsp', cat: 'pantry' },
      { name: 'vegetable oil', qty: '1', unit: 'tbsp', cat: 'pantry' },
    ],
  },
  {
    id: 'mild-butter-chicken',
    name: 'Mild Butter Chicken with Rice',
    cuisine: 'Indian (mild)',
    mealType: 'dinner',
    prepMin: 35,
    freezerFriendly: true,
    foodGroups: ['protein-poultry', 'dairy', 'grain-rice'],
    toddlerNotes: 'Skip chili entirely, keep sauce mild and creamy; blend smoother for the 2yo if needed.',
    steps: [
      'Sear diced chicken in butter, set aside.',
      'Soften onion and garlic, add tomato passata and cream.',
      'Simmer with mild curry powder, return chicken to sauce.',
      'Serve over rice.',
    ],
    ingredients: [
      { name: 'chicken thigh', qty: '500', unit: 'g', cat: 'protein' },
      { name: 'butter', qty: '30', unit: 'g', cat: 'dairy' },
      { name: 'onion', qty: '1', unit: '', cat: 'produce' },
      { name: 'garlic', qty: '2', unit: 'cloves', cat: 'produce' },
      { name: 'tomato passata', qty: '400', unit: 'g', cat: 'pantry' },
      { name: 'cream', qty: '100', unit: 'ml', cat: 'dairy' },
      { name: 'mild curry powder', qty: '1', unit: 'tsp', cat: 'spice' },
      { name: 'rice', qty: '300', unit: 'g', cat: 'pantry' },
    ],
  },
  {
    id: 'turkey-bolognese',
    name: 'Turkey Bolognese with Pasta',
    cuisine: 'Italian',
    mealType: 'dinner',
    prepMin: 30,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['protein-poultry', 'veg', 'grain-pasta'],
    toddlerNotes: 'Blitz the sauce a little smoother and use small pasta shapes for easier self-feeding.',
    steps: [
      'Soften onion, carrot and celery in oil.',
      'Add turkey mince, brown well.',
      'Add chopped tomatoes and a little stock, simmer 20 min.',
      'Serve over cooked pasta.',
    ],
    ingredients: [
      { name: 'turkey mince', qty: '400', unit: 'g', cat: 'protein' },
      { name: 'pasta', qty: '350', unit: 'g', cat: 'pantry' },
      { name: 'onion', qty: '1', unit: '', cat: 'produce' },
      { name: 'carrot', qty: '1', unit: '', cat: 'produce' },
      { name: 'celery', qty: '1', unit: 'stick', cat: 'produce' },
      { name: 'chopped tomatoes', qty: '400', unit: 'g', cat: 'pantry' },
      { name: 'olive oil', qty: '1', unit: 'tbsp', cat: 'pantry' },
      { name: 'dried oregano', qty: '1', unit: 'tsp', cat: 'spice' },
    ],
    it: {
      name: 'Ragù di tacchino con pasta',
      toddlerNotes: 'Frulla leggermente il sugo per renderlo più omogeneo e usa formati di pasta piccoli, più facili da mangiare da soli.',
      steps: [
        'Soffriggere cipolla, carota e sedano tritati in olio.',
        'Aggiungere la carne di tacchino macinata e rosolare bene.',
        'Unire i pomodori pelati e un po\' di brodo, cuocere a fuoco lento per 20 minuti.',
        'Servire con la pasta cotta.',
      ],
    },
  },
  {
    id: 'salmon-sweet-potato-mash',
    name: 'Salmon & Sweet Potato Mash',
    cuisine: 'European',
    mealType: 'dinner',
    prepMin: 25,
    freezerFriendly: false,
    foodGroups: ['protein-fish', 'veg', 'omega3'],
    toddlerNotes: 'Flake salmon carefully and double-check for bones; mash sweet potato smooth for the 2yo.',
    steps: [
      'Bake or pan-fry salmon fillets until just cooked.',
      'Boil sweet potato until soft, mash with a little butter.',
      'Steam broccoli or green beans on the side.',
      'Flake salmon over mash to serve.',
    ],
    ingredients: [
      { name: 'salmon fillet', qty: '400', unit: 'g', cat: 'protein' },
      { name: 'sweet potato', qty: '600', unit: 'g', cat: 'produce' },
      { name: 'butter', qty: '20', unit: 'g', cat: 'dairy' },
      { name: 'broccoli', qty: '1', unit: 'head', cat: 'produce' },
      { name: 'lemon', qty: '1', unit: '', cat: 'produce' },
    ],
  },
  {
    id: 'veggie-cheese-quesadillas',
    name: 'Veggie & Cheese Quesadillas',
    cuisine: 'Mexican-inspired',
    mealType: 'lunch',
    prepMin: 15,
    freezerFriendly: false,
    foodGroups: ['dairy', 'veg', 'grain-wheat'],
    toddlerNotes: 'Cut into small triangles or strips — great finger food for the 2yo.',
    steps: [
      'Finely dice bell pepper and sweetcorn.',
      'Scatter cheese and veg over half a tortilla, fold over.',
      'Toast in a dry pan until golden and cheese melts.',
      'Cut into wedges.',
    ],
    ingredients: [
      { name: 'tortilla wraps', qty: '4', unit: '', cat: 'pantry' },
      { name: 'cheddar cheese', qty: '150', unit: 'g', cat: 'dairy' },
      { name: 'bell pepper', qty: '1', unit: '', cat: 'produce' },
      { name: 'sweetcorn', qty: '100', unit: 'g', cat: 'pantry' },
    ],
  },
  {
    id: 'greek-chicken-bowls',
    name: 'Greek-style Chicken Bowls',
    cuisine: 'Mediterranean',
    mealType: 'dinner',
    prepMin: 30,
    freezerFriendly: false,
    foodGroups: ['protein-poultry', 'veg', 'dairy', 'grain-rice'],
    toddlerNotes: 'Serve components separately (deconstructed) so the 2yo can pick plain chicken, rice, and soft cucumber.',
    steps: [
      'Marinate diced chicken in lemon, garlic and olive oil briefly.',
      'Pan-fry or grill chicken until cooked through.',
      'Serve over rice with diced cucumber, tomato and a spoon of yoghurt.',
    ],
    ingredients: [
      { name: 'chicken breast', qty: '400', unit: 'g', cat: 'protein' },
      { name: 'lemon', qty: '1', unit: '', cat: 'produce' },
      { name: 'garlic', qty: '2', unit: 'cloves', cat: 'produce' },
      { name: 'olive oil', qty: '2', unit: 'tbsp', cat: 'pantry' },
      { name: 'rice', qty: '300', unit: 'g', cat: 'pantry' },
      { name: 'cucumber', qty: '1', unit: '', cat: 'produce' },
      { name: 'tomato', qty: '2', unit: '', cat: 'produce' },
      { name: 'greek yoghurt', qty: '150', unit: 'g', cat: 'dairy' },
    ],
  },
  {
    id: 'homemade-fish-fingers',
    name: 'Homemade Fish Fingers & Peas',
    cuisine: 'British comfort',
    mealType: 'dinner',
    prepMin: 30,
    freezerFriendly: true,
    foodGroups: ['protein-fish', 'veg', 'grain-wheat'],
    toddlerNotes: 'Cut fish into small finger-shaped strips before crumbing — easy to pick up and eat.',
    steps: [
      'Cut white fish into strips, pat dry.',
      'Coat in flour, then beaten egg, then breadcrumbs.',
      'Bake or shallow-fry until golden and cooked through.',
      'Serve with peas and a wedge of lemon.',
    ],
    ingredients: [
      { name: 'white fish fillet', qty: '400', unit: 'g', cat: 'protein' },
      { name: 'flour', qty: '50', unit: 'g', cat: 'pantry' },
      { name: 'egg', qty: '1', unit: '', cat: 'dairy' },
      { name: 'breadcrumbs', qty: '100', unit: 'g', cat: 'pantry' },
      { name: 'frozen peas', qty: '200', unit: 'g', cat: 'frozen' },
      { name: 'lemon', qty: '1', unit: '', cat: 'produce' },
    ],
  },
  {
    id: 'mini-meatballs-tomato',
    name: 'Mini Meatballs in Tomato Sauce',
    cuisine: 'Italian',
    mealType: 'dinner',
    prepMin: 35,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['protein-beef', 'veg', 'grain-pasta'],
    toddlerNotes: 'Roll meatballs bite-sized for the 2yo (half the size of the 5yo\'s) so they cook through fast and are easy to eat whole.',
    steps: [
      'Mix mince with breadcrumbs, egg and a little garlic; roll small balls.',
      'Brown meatballs in a pan.',
      'Add chopped tomatoes, simmer 15-20 min until cooked through.',
      'Serve with pasta or crusty bread.',
    ],
    ingredients: [
      { name: 'beef mince', qty: '400', unit: 'g', cat: 'protein' },
      { name: 'breadcrumbs', qty: '50', unit: 'g', cat: 'pantry' },
      { name: 'egg', qty: '1', unit: '', cat: 'dairy' },
      { name: 'garlic', qty: '1', unit: 'clove', cat: 'produce' },
      { name: 'chopped tomatoes', qty: '400', unit: 'g', cat: 'pantry' },
      { name: 'pasta', qty: '300', unit: 'g', cat: 'pantry' },
    ],
    it: {
      name: 'Polpette al sugo di pomodoro',
      toddlerNotes: 'Forma le polpette piccole (la metà rispetto a quelle per la bambina di 5 anni) per il bimbo di 2 anni, così cuociono velocemente e si mangiano facilmente intere.',
      steps: [
        'Mescolare la carne macinata con pangrattato, uovo e un po\' di aglio; formare delle palline piccole.',
        'Rosolare le polpette in padella.',
        'Aggiungere i pomodori pelati e cuocere a fuoco lento per 15-20 minuti, finché cotte.',
        'Servire con pasta o pane.',
      ],
    },
  },
  {
    id: 'veggie-egg-fried-rice',
    name: 'Veggie Egg Fried Rice',
    cuisine: 'Asian-inspired',
    mealType: 'lunch',
    prepMin: 15,
    freezerFriendly: false,
    foodGroups: ['veg', 'protein-egg', 'grain-rice'],
    toddlerNotes: 'A good vegetarian lunch — dice veg finely and serve slightly cooled.',
    steps: [
      'Scramble eggs softly, set aside.',
      'Stir-fry diced carrot, sweetcorn and peas.',
      'Add cooked rice and egg back in, splash of soy sauce, toss together.',
    ],
    ingredients: [
      { name: 'rice', qty: '250', unit: 'g', cat: 'pantry' },
      { name: 'egg', qty: '3', unit: '', cat: 'dairy' },
      { name: 'carrot', qty: '1', unit: '', cat: 'produce' },
      { name: 'sweetcorn', qty: '80', unit: 'g', cat: 'pantry' },
      { name: 'frozen peas', qty: '100', unit: 'g', cat: 'frozen' },
      { name: 'soy sauce', qty: '1', unit: 'tbsp', cat: 'pantry' },
      { name: 'vegetable oil', qty: '1', unit: 'tbsp', cat: 'pantry' },
    ],
  },
  {
    id: 'creamy-salmon-pasta',
    name: 'Creamy Salmon Pasta',
    cuisine: 'Italian/European',
    mealType: 'dinner',
    prepMin: 25,
    freezerFriendly: false,
    foodGroups: ['protein-fish', 'dairy', 'grain-pasta'],
    toddlerNotes: 'Flake salmon well and check carefully for bones; use small pasta shapes.',
    steps: [
      'Cook pasta until al dente.',
      'Flake cooked or tinned salmon into a light cream sauce with peas.',
      'Toss through pasta, finish with a squeeze of lemon.',
    ],
    ingredients: [
      { name: 'pasta', qty: '350', unit: 'g', cat: 'pantry' },
      { name: 'salmon fillet', qty: '300', unit: 'g', cat: 'protein' },
      { name: 'cream', qty: '150', unit: 'ml', cat: 'dairy' },
      { name: 'frozen peas', qty: '100', unit: 'g', cat: 'frozen' },
      { name: 'lemon', qty: '1', unit: '', cat: 'produce' },
      { name: 'garlic', qty: '1', unit: 'clove', cat: 'produce' },
    ],
  },
  {
    id: 'chickpea-veggie-curry',
    name: 'Chickpea & Veggie Curry',
    cuisine: 'Indian (mild)',
    mealType: 'dinner',
    prepMin: 30,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['legume', 'veg', 'grain-rice'],
    toddlerNotes: 'Mild and naturally soft — mash slightly for the 2yo, serve with plain rice.',
    steps: [
      'Soften onion and garlic, add mild curry powder.',
      'Add chickpeas, chopped tomatoes and diced sweet potato.',
      'Simmer until sweet potato is tender, stir through spinach at the end.',
      'Serve with rice.',
    ],
    ingredients: [
      { name: 'chickpeas (tin)', qty: '2', unit: 'tins', cat: 'pantry' },
      { name: 'onion', qty: '1', unit: '', cat: 'produce' },
      { name: 'garlic', qty: '2', unit: 'cloves', cat: 'produce' },
      { name: 'sweet potato', qty: '300', unit: 'g', cat: 'produce' },
      { name: 'chopped tomatoes', qty: '400', unit: 'g', cat: 'pantry' },
      { name: 'spinach', qty: '100', unit: 'g', cat: 'produce' },
      { name: 'mild curry powder', qty: '1', unit: 'tsp', cat: 'spice' },
      { name: 'rice', qty: '300', unit: 'g', cat: 'pantry' },
    ],
    it: {
      name: 'Curry di ceci e verdure (delicato)',
      toddlerNotes: 'Sapore delicato e consistenza naturalmente morbida — schiaccia leggermente per il bimbo di 2 anni e servi con riso semplice.',
      steps: [
        'Soffriggere cipolla e aglio, aggiungere il curry delicato.',
        'Unire i ceci, i pomodori pelati e la patata dolce a cubetti.',
        'Cuocere finché la patata dolce è morbida, aggiungere gli spinaci alla fine.',
        'Servire con riso.',
      ],
    },
  },
  {
    id: 'homemade-veggie-pizza',
    name: 'Homemade Pizza with Veggie Toppings',
    cuisine: 'Italian',
    mealType: 'dinner',
    prepMin: 40,
    freezerFriendly: true,
    foodGroups: ['dairy', 'veg', 'grain-wheat'],
    toddlerNotes: 'Let the 5yo help top their own mini pizza; cut the 2yo\'s slice into small strips.',
    steps: [
      'Roll out pizza dough (fresh or shop-bought base).',
      'Spread tomato sauce, scatter mozzarella and diced veg toppings.',
      'Bake until crust is golden and cheese bubbling.',
    ],
    ingredients: [
      { name: 'pizza dough', qty: '2', unit: 'balls', cat: 'pantry' },
      { name: 'tomato passata', qty: '200', unit: 'g', cat: 'pantry' },
      { name: 'mozzarella', qty: '250', unit: 'g', cat: 'dairy' },
      { name: 'bell pepper', qty: '1', unit: '', cat: 'produce' },
      { name: 'mushroom', qty: '100', unit: 'g', cat: 'produce' },
    ],
  },
  {
    id: 'beef-veggie-stirfry-noodles',
    name: 'Beef & Veggie Stir-fry with Noodles',
    cuisine: 'Asian-inspired',
    mealType: 'dinner',
    prepMin: 25,
    freezerFriendly: false,
    foodGroups: ['protein-beef', 'veg', 'grain-noodle'],
    toddlerNotes: 'Cut beef and veg into small, soft-cooked pieces; go light on soy sauce for the toddler portion.',
    steps: [
      'Cook noodles per pack instructions.',
      'Stir-fry thin-sliced beef until browned, remove.',
      'Stir-fry sliced pepper, carrot and broccoli, return beef.',
      'Add noodles and soy-garlic sauce, toss together.',
    ],
    ingredients: [
      { name: 'beef strips', qty: '350', unit: 'g', cat: 'protein' },
      { name: 'noodles', qty: '300', unit: 'g', cat: 'pantry' },
      { name: 'bell pepper', qty: '1', unit: '', cat: 'produce' },
      { name: 'carrot', qty: '1', unit: '', cat: 'produce' },
      { name: 'broccoli', qty: '1', unit: 'head', cat: 'produce' },
      { name: 'garlic', qty: '2', unit: 'cloves', cat: 'produce' },
      { name: 'soy sauce', qty: '2', unit: 'tbsp', cat: 'pantry' },
    ],
  },
  {
    id: 'baked-chicken-tenders-veg',
    name: 'Baked Chicken Tenders with Roasted Veg',
    cuisine: 'American-ish (healthier)',
    mealType: 'dinner',
    prepMin: 35,
    freezerFriendly: true,
    foodGroups: ['protein-poultry', 'veg', 'grain-wheat'],
    toddlerNotes: 'Cut tenders into smaller strips post-bake; roast veg until very soft for easy chewing.',
    steps: [
      'Coat chicken strips in flour, egg, then breadcrumbs.',
      'Bake until golden and cooked through.',
      'Toss carrot and courgette wedges in oil, roast alongside.',
    ],
    ingredients: [
      { name: 'chicken breast', qty: '450', unit: 'g', cat: 'protein' },
      { name: 'flour', qty: '50', unit: 'g', cat: 'pantry' },
      { name: 'egg', qty: '1', unit: '', cat: 'dairy' },
      { name: 'breadcrumbs', qty: '100', unit: 'g', cat: 'pantry' },
      { name: 'carrot', qty: '2', unit: '', cat: 'produce' },
      { name: 'courgette', qty: '1', unit: '', cat: 'produce' },
      { name: 'olive oil', qty: '1', unit: 'tbsp', cat: 'pantry' },
    ],
  },
  {
    id: 'lentil-veggie-soup',
    name: 'Lentil & Veggie Soup with Bread',
    cuisine: 'French/European',
    mealType: 'lunch',
    prepMin: 35,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['legume', 'veg', 'grain-wheat'],
    toddlerNotes: 'Naturally soft and mashable — blend part of it smoother for the 2yo if preferred.',
    steps: [
      'Soften onion, carrot and celery in oil.',
      'Add red lentils, stock and chopped tomatoes.',
      'Simmer 20-25 min until lentils are soft.',
      'Serve with crusty bread.',
    ],
    ingredients: [
      { name: 'red lentils', qty: '200', unit: 'g', cat: 'pantry' },
      { name: 'onion', qty: '1', unit: '', cat: 'produce' },
      { name: 'carrot', qty: '2', unit: '', cat: 'produce' },
      { name: 'celery', qty: '1', unit: 'stick', cat: 'produce' },
      { name: 'chopped tomatoes', qty: '400', unit: 'g', cat: 'pantry' },
      { name: 'vegetable stock cube', qty: '1', unit: '', cat: 'pantry' },
      { name: 'bread', qty: '1', unit: 'loaf', cat: 'pantry' },
    ],
    it: {
      name: 'Zuppa di lenticchie e verdure con pane',
      toddlerNotes: 'Consistenza naturalmente morbida e facile da schiacciare — frulla parzialmente la zuppa per il piccolo di 2 anni, se preferisce una consistenza più liscia.',
      steps: [
        'Soffriggere cipolla, carota e sedano in olio.',
        'Aggiungere le lenticchie rosse, il brodo e i pomodori pelati.',
        'Cuocere a fuoco lento per 20-25 minuti, finché le lenticchie sono morbide.',
        'Servire con pane fresco.',
      ],
    },
  },
  {
    id: 'pancakes-with-fruit',
    name: 'Pancakes with Fruit',
    cuisine: 'European',
    mealType: 'breakfast',
    prepMin: 20,
    freezerFriendly: true,
    foodGroups: ['dairy', 'fruit', 'grain-wheat'],
    toddlerNotes: 'Make silver-dollar size for easy little hands; top with mashed banana instead of syrup.',
    steps: [
      'Whisk flour, egg and milk into a smooth batter.',
      'Cook small pancakes in a lightly buttered pan.',
      'Serve with sliced banana and berries.',
    ],
    ingredients: [
      { name: 'flour', qty: '200', unit: 'g', cat: 'pantry' },
      { name: 'egg', qty: '2', unit: '', cat: 'dairy' },
      { name: 'milk', qty: '300', unit: 'ml', cat: 'dairy' },
      { name: 'banana', qty: '2', unit: '', cat: 'produce' },
      { name: 'berries', qty: '150', unit: 'g', cat: 'produce' },
      { name: 'butter', qty: '20', unit: 'g', cat: 'dairy' },
    ],
  },
  {
    id: 'overnight-oats-berries',
    name: 'Overnight Oats with Berries',
    cuisine: 'European',
    mealType: 'breakfast',
    prepMin: 5,
    freezerFriendly: false,
    foodGroups: ['grain-oat', 'dairy', 'fruit'],
    toddlerNotes: 'Blend smoother for the 2yo, or swap yoghurt for a bit more milk to loosen texture.',
    steps: [
      'Mix oats, milk and yoghurt in a jar.',
      'Top with chopped berries.',
      'Chill overnight, stir before serving.',
    ],
    ingredients: [
      { name: 'rolled oats', qty: '150', unit: 'g', cat: 'pantry' },
      { name: 'milk', qty: '300', unit: 'ml', cat: 'dairy' },
      { name: 'greek yoghurt', qty: '150', unit: 'g', cat: 'dairy' },
      { name: 'berries', qty: '150', unit: 'g', cat: 'produce' },
    ],
  },
  {
    id: 'tuna-sweetcorn-pasta-salad',
    name: 'Tuna & Sweetcorn Pasta Salad',
    cuisine: 'European',
    mealType: 'lunch',
    prepMin: 15,
    freezerFriendly: false,
    foodGroups: ['protein-fish', 'veg', 'grain-pasta'],
    toddlerNotes: 'Serve slightly warm rather than cold if the 2yo prefers; dice cucumber small.',
    steps: [
      'Cook pasta, cool slightly.',
      'Flake tuna, mix with sweetcorn, diced cucumber and a little mayo or yoghurt.',
      'Toss through pasta.',
    ],
    ingredients: [
      { name: 'pasta', qty: '300', unit: 'g', cat: 'pantry' },
      { name: 'tuna (tin)', qty: '2', unit: 'tins', cat: 'pantry' },
      { name: 'sweetcorn', qty: '100', unit: 'g', cat: 'pantry' },
      { name: 'cucumber', qty: '1', unit: '', cat: 'produce' },
      { name: 'mayonnaise', qty: '2', unit: 'tbsp', cat: 'pantry' },
    ],
  },
  {
    id: 'veggie-packed-lasagne',
    name: 'Veggie-Packed Lasagne',
    cuisine: 'Italian',
    mealType: 'dinner',
    prepMin: 60,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['protein-beef', 'veg', 'dairy', 'grain-wheat'],
    toddlerNotes: 'Grate or finely dice the vegetables into the ragù so they melt into the sauce — the 2yo won\'t spot them, and cut the 5yo\'s portion into small squares.',
    steps: [
      'Make a soffritto with finely diced/grated onion, carrot, celery and courgette in olive oil.',
      'Add beef mince, brown well, then stir in chopped tomatoes and simmer 25 min.',
      'Make a simple white (béchamel) sauce with butter, flour and milk.',
      'Layer lasagne sheets, ragù, béchamel and grated parmesan in a dish, repeat, top with cheese.',
      'Bake until golden and bubbling.',
    ],
    ingredients: [
      { name: 'beef mince', qty: '400', unit: 'g', cat: 'protein' },
      { name: 'lasagne sheets', qty: '250', unit: 'g', cat: 'pantry' },
      { name: 'onion', qty: '1', unit: '', cat: 'produce' },
      { name: 'carrot', qty: '2', unit: '', cat: 'produce' },
      { name: 'celery', qty: '1', unit: 'stick', cat: 'produce' },
      { name: 'courgette', qty: '1', unit: '', cat: 'produce' },
      { name: 'chopped tomatoes', qty: '400', unit: 'g', cat: 'pantry' },
      { name: 'butter', qty: '40', unit: 'g', cat: 'dairy' },
      { name: 'flour', qty: '40', unit: 'g', cat: 'pantry' },
      { name: 'milk', qty: '500', unit: 'ml', cat: 'dairy' },
      { name: 'parmesan', qty: '80', unit: 'g', cat: 'dairy' },
    ],
    it: {
      name: 'Lasagne con verdure nascoste',
      toddlerNotes: 'Grattugia o taglia le verdure molto fini nel ragù così si "nascondono" nel sugo — il piccolo di 2 anni non se ne accorgerà; taglia la porzione della bambina di 5 anni a quadretti piccoli.',
      steps: [
        'Preparare un soffritto con cipolla, carota, sedano e zucchina tagliati finemente o grattugiati, in olio d\'oliva.',
        'Aggiungere la carne macinata, rosolare bene, poi unire i pomodori pelati e cuocere a fuoco lento per 25 minuti.',
        'Preparare una besciamella semplice con burro, farina e latte.',
        'Alternare in una teglia sfoglie di lasagne, ragù, besciamella e parmigiano grattugiato; ripetere gli strati e finire con formaggio in superficie.',
        'Cuocere in forno finché non è dorata e bollente.',
      ],
    },
  },
  {
    id: 'veggie-polpette',
    name: 'Veggie Polpette (Veggie Meatballs)',
    cuisine: 'Italian',
    mealType: 'dinner',
    prepMin: 40,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['veg', 'dairy', 'grain-wheat'],
    toddlerNotes: 'Grate vegetables finely so the polpette hold together and feel familiar in texture to regular meatballs; roll bite-sized for the 2yo.',
    steps: [
      'Grate courgette and carrot, squeeze out excess water.',
      'Mix with mashed potato, breadcrumbs, parmesan and egg to bind.',
      'Roll into small balls, bake or shallow-fry until golden.',
      'Serve with tomato sauce.',
    ],
    ingredients: [
      { name: 'courgette', qty: '2', unit: '', cat: 'produce' },
      { name: 'carrot', qty: '2', unit: '', cat: 'produce' },
      { name: 'potato', qty: '2', unit: '', cat: 'produce' },
      { name: 'breadcrumbs', qty: '80', unit: 'g', cat: 'pantry' },
      { name: 'parmesan', qty: '50', unit: 'g', cat: 'dairy' },
      { name: 'egg', qty: '1', unit: '', cat: 'dairy' },
      { name: 'tomato passata', qty: '300', unit: 'g', cat: 'pantry' },
    ],
    it: {
      name: 'Polpette di verdure',
      toddlerNotes: 'Grattugia le verdure molto fini così le polpette si compattano bene e la consistenza ricorda quella delle polpette di carne classiche; forma polpette piccole per il bimbo di 2 anni.',
      steps: [
        'Grattugiare zucchine e carote, strizzare bene per eliminare l\'acqua in eccesso.',
        'Mescolare con patate lessate e schiacciate, pangrattato, parmigiano e un uovo per legare.',
        'Formare delle polpettine piccole e cuocere in forno o in padella finché dorate.',
        'Servire con passata di pomodoro.',
      ],
    },
  },
  {
    id: 'pasta-alla-norma',
    name: 'Pasta alla Norma (Sicilian Eggplant Pasta)',
    cuisine: 'Sicilian',
    mealType: 'dinner',
    prepMin: 35,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['veg', 'dairy', 'grain-pasta'],
    toddlerNotes: 'Dice the aubergine small and roast until very soft so it melts into the sauce — the 2yo won\'t notice it\'s there; go light on the ricotta salata for little ones.',
    steps: [
      'Dice aubergine, salt lightly and roast or pan-fry until soft and golden.',
      'Make a simple tomato sauce with garlic and basil.',
      'Stir the roasted aubergine through the sauce.',
      'Toss with cooked pasta, top with grated ricotta salata (or parmesan).',
    ],
    ingredients: [
      { name: 'aubergine', qty: '1', unit: 'large', cat: 'produce' },
      { name: 'pasta', qty: '350', unit: 'g', cat: 'pantry' },
      { name: 'chopped tomatoes', qty: '400', unit: 'g', cat: 'pantry' },
      { name: 'garlic', qty: '2', unit: 'cloves', cat: 'produce' },
      { name: 'basil', qty: '1', unit: 'handful', cat: 'produce' },
      { name: 'ricotta salata', qty: '80', unit: 'g', cat: 'dairy' },
      { name: 'olive oil', qty: '2', unit: 'tbsp', cat: 'pantry' },
    ],
    it: {
      name: 'Pasta alla Norma (melanzane siciliana)',
      toddlerNotes: 'Taglia le melanzane a dadini piccoli e cuocile finché morbidissime, così si "sciolgono" nel sugo — il piccolo di 2 anni non se ne accorgerà; usa poca ricotta salata per i più piccoli.',
      steps: [
        'Tagliare le melanzane a dadini, salarle leggermente e cuocerle in forno o in padella finché morbide e dorate.',
        'Preparare un sugo di pomodoro semplice con aglio e basilico.',
        'Unire le melanzane cotte al sugo.',
        'Condire la pasta cotta con il sugo, guarnire con ricotta salata grattugiata (o parmigiano).',
      ],
    },
  },
  {
    id: 'sicilian-baked-chicken-lemon',
    name: 'Sicilian Baked Chicken with Lemon & Potatoes',
    cuisine: 'Sicilian',
    mealType: 'dinner',
    prepMin: 50,
    freezerFriendly: false,
    foodGroups: ['protein-poultry', 'veg'],
    toddlerNotes: 'Leave olives out of (or on the side of) the toddler\'s portion since the pits and strong flavour aren\'t toddler-friendly; cut chicken and potatoes into small pieces.',
    steps: [
      'Toss chicken thighs and potato wedges with olive oil, lemon juice, garlic and oregano.',
      'Scatter olives around the tray.',
      'Roast until chicken is cooked through and potatoes are golden.',
      'Serve with the pan juices spooned over.',
    ],
    ingredients: [
      { name: 'chicken thigh', qty: '600', unit: 'g', cat: 'protein' },
      { name: 'potato', qty: '500', unit: 'g', cat: 'produce' },
      { name: 'lemon', qty: '1', unit: '', cat: 'produce' },
      { name: 'garlic', qty: '3', unit: 'cloves', cat: 'produce' },
      { name: 'olives', qty: '80', unit: 'g', cat: 'pantry' },
      { name: 'dried oregano', qty: '1', unit: 'tsp', cat: 'spice' },
      { name: 'olive oil', qty: '2', unit: 'tbsp', cat: 'pantry' },
    ],
  },
  {
    id: 'caponata',
    name: 'Caponata (Sicilian Sweet & Sour Vegetables)',
    cuisine: 'Sicilian',
    mealType: 'lunch',
    prepMin: 45,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['veg', 'legume'],
    toddlerNotes: 'Dice everything small and cook until very soft; go easy on the vinegar for the toddler portion and serve with plenty of bread to scoop.',
    steps: [
      'Dice aubergine, celery and onion; fry aubergine until golden, set aside.',
      'Soften onion and celery, add chopped tomatoes, capers and olives.',
      'Stir in a little vinegar and a pinch of sugar, simmer to a sweet-sour balance.',
      'Return aubergine to the pan, simmer 10 more minutes.',
      'Serve warm or at room temperature with crusty bread.',
    ],
    ingredients: [
      { name: 'aubergine', qty: '2', unit: '', cat: 'produce' },
      { name: 'celery', qty: '2', unit: 'sticks', cat: 'produce' },
      { name: 'onion', qty: '1', unit: '', cat: 'produce' },
      { name: 'chopped tomatoes', qty: '300', unit: 'g', cat: 'pantry' },
      { name: 'capers', qty: '1', unit: 'tbsp', cat: 'pantry' },
      { name: 'olives', qty: '50', unit: 'g', cat: 'pantry' },
      { name: 'red wine vinegar', qty: '1', unit: 'tbsp', cat: 'pantry' },
      { name: 'bread', qty: '1', unit: 'loaf', cat: 'pantry' },
    ],
    it: {
      name: 'Caponata siciliana',
      toddlerNotes: 'Taglia tutto a dadini piccoli e cuoci finché molto morbido; usa poco aceto nella porzione del piccolo e servi con tanto pane per la scarpetta.',
      steps: [
        'Tagliare a dadini melanzane, sedano e cipolla; friggere le melanzane finché dorate e metterle da parte.',
        'Rosolare cipolla e sedano, aggiungere i pomodori pelati, i capperi e le olive.',
        'Aggiungere un po\' di aceto e un pizzico di zucchero, cuocere per bilanciare il sapore agrodolce.',
        'Rimettere le melanzane in padella e cuocere altri 10 minuti.',
        'Servire tiepida o a temperatura ambiente con pane fresco.',
      ],
    },
  },
  {
    id: 'baked-arancini-rice-balls',
    name: 'Baked Arancini-Style Rice Balls',
    cuisine: 'Sicilian',
    mealType: 'lunch',
    prepMin: 45,
    freezerFriendly: true,
    oscarFriendly: true,
    foodGroups: ['grain-rice', 'veg', 'dairy'],
    toddlerNotes: 'Perfect finger food — make them golf-ball sized for the 5yo and smaller bite-sized ones for the 2yo; baking instead of deep-frying keeps them lighter.',
    steps: [
      'Cook rice, stir in grated parmesan and a beaten egg while warm, let cool.',
      'Mix in finely diced peas and carrot.',
      'Shape into balls, roll in breadcrumbs.',
      'Bake until golden and crisp outside.',
    ],
    ingredients: [
      { name: 'rice', qty: '300', unit: 'g', cat: 'pantry' },
      { name: 'parmesan', qty: '60', unit: 'g', cat: 'dairy' },
      { name: 'egg', qty: '2', unit: '', cat: 'dairy' },
      { name: 'frozen peas', qty: '80', unit: 'g', cat: 'frozen' },
      { name: 'carrot', qty: '1', unit: '', cat: 'produce' },
      { name: 'breadcrumbs', qty: '100', unit: 'g', cat: 'pantry' },
    ],
    it: {
      name: 'Arancini al forno',
      toddlerNotes: 'Un ottimo cibo da mangiare con le mani — falli grandi come una pallina da golf per la bambina di 5 anni e più piccoli per il bimbo di 2 anni; cuocerli al forno invece che friggerli li rende più leggeri.',
      steps: [
        'Cuocere il riso, mescolare con parmigiano grattugiato e un uovo sbattuto mentre è ancora caldo, lasciar raffreddare.',
        'Aggiungere piselli e carota tagliati finemente.',
        'Formare delle palline e passarle nel pangrattato.',
        'Cuocere in forno finché dorate e croccanti fuori.',
      ],
    },
  },
  {
    id: 'greek-orzo-tomato-feta',
    name: 'Greek Orzo with Tomato & Feta',
    cuisine: 'Greek/Mediterranean',
    mealType: 'lunch',
    prepMin: 20,
    freezerFriendly: false,
    foodGroups: ['veg', 'dairy', 'grain-wheat'],
    toddlerNotes: 'Crumble the feta very small and dice tomatoes small; a mild, soft one-pot meal that\'s easy for little ones to self-feed.',
    steps: [
      'Cook orzo in stock until just tender.',
      'Stir through diced tomato, a little olive oil and crumbled feta.',
      'Finish with chopped fresh herbs if you have them.',
    ],
    ingredients: [
      { name: 'orzo', qty: '300', unit: 'g', cat: 'pantry' },
      { name: 'vegetable stock cube', qty: '1', unit: '', cat: 'pantry' },
      { name: 'tomato', qty: '3', unit: '', cat: 'produce' },
      { name: 'feta', qty: '150', unit: 'g', cat: 'dairy' },
      { name: 'olive oil', qty: '1', unit: 'tbsp', cat: 'pantry' },
    ],
  },
];

// English ingredient name (lowercase) -> Italian, used when generating Oscar's Italian brief.
const ITALIAN_INGREDIENTS = {
  'turkey mince': 'carne di tacchino macinata',
  'pasta': 'pasta',
  'onion': 'cipolla',
  'carrot': 'carota',
  'celery': 'sedano',
  'chopped tomatoes': 'pomodori pelati',
  'olive oil': "olio d'oliva",
  'dried oregano': 'origano secco',
  'beef mince': 'carne di manzo macinata',
  'breadcrumbs': 'pangrattato',
  'egg': 'uovo',
  'garlic': 'aglio',
  'red lentils': 'lenticchie rosse',
  'vegetable stock cube': 'dado vegetale',
  'bread': 'pane',
  'chickpeas (tin)': 'ceci (in scatola)',
  'sweet potato': 'patata dolce',
  'spinach': 'spinaci',
  'mild curry powder': 'curry delicato',
  'rice': 'riso',
  'lasagne sheets': 'sfoglie di lasagne',
  'courgette': 'zucchina',
  'butter': 'burro',
  'flour': 'farina',
  'milk': 'latte',
  'parmesan': 'parmigiano',
  'potato': 'patata',
  'tomato passata': 'passata di pomodoro',
  'aubergine': 'melanzana',
  'ricotta salata': 'ricotta salata',
  'basil': 'basilico',
  'capers': 'capperi',
  'olives': 'olive',
  'red wine vinegar': 'aceto di vino rosso',
  'frozen peas': 'piselli surgelati',
};
